# Generated by Django 6.0.3 on 2026-03-28 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_comment_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="liked_users",
            field=models.ManyToManyField(
                related_name="liked_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
